[package]
name = "http_request2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = "2.3.2"
async-std = {version = "1.10.0", features = ["attributes"]}